// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package se.test.domain;

import org.springframework.beans.factory.annotation.Configurable;
import se.test.domain.Customer;

privileged aspect Customer_Roo_Configurable {
    
    declare @type: Customer: @Configurable;
    
}
