// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package se.test.domain;

import java.util.Date;
import se.test.domain.Customer;

privileged aspect Customer_Roo_JavaBean {
    
    public String Customer.getName() {
        return this.name;
    }
    
    public void Customer.setName(String name) {
        this.name = name;
    }
    
    public String Customer.getLastname() {
        return this.Lastname;
    }
    
    public void Customer.setLastname(String Lastname) {
        this.Lastname = Lastname;
    }
    
    public int Customer.getAge() {
        return this.age;
    }
    
    public void Customer.setAge(int age) {
        this.age = age;
    }
    
    public Date Customer.getDuedate() {
        return this.duedate;
    }
    
    public void Customer.setDuedate(Date duedate) {
        this.duedate = duedate;
    }
    
}
