// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package se.test.domain;

import se.test.domain.Memo;

privileged aspect Memo_Roo_JavaBean {
    
    public String Memo.getSubject() {
        return this.subject;
    }
    
    public void Memo.setSubject(String subject) {
        this.subject = subject;
    }
    
}
