// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package se.test.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;
import se.test.domain.Memo;

privileged aspect Memo_Roo_Jpa_Entity {
    
    declare @type: Memo: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Memo.id;
    
    @Version
    @Column(name = "version")
    private Integer Memo.version;
    
    public Long Memo.getId() {
        return this.id;
    }
    
    public void Memo.setId(Long id) {
        this.id = id;
    }
    
    public Integer Memo.getVersion() {
        return this.version;
    }
    
    public void Memo.setVersion(Integer version) {
        this.version = version;
    }
    
}
