// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package se.test.domain;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;
import se.test.domain.Memo;

privileged aspect Memo_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Memo.entityManager;
    
    public static final EntityManager Memo.entityManager() {
        EntityManager em = new Memo().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Memo.countMemoes() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Memo o", Long.class).getSingleResult();
    }
    
    public static List<Memo> Memo.findAllMemoes() {
        return entityManager().createQuery("SELECT o FROM Memo o", Memo.class).getResultList();
    }
    
    public static Memo Memo.findMemo(Long id) {
        if (id == null) return null;
        return entityManager().find(Memo.class, id);
    }
    
    public static List<Memo> Memo.findMemoEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Memo o", Memo.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Memo.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Memo.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Memo attached = Memo.findMemo(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Memo.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Memo.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Memo Memo.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Memo merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
