// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package se.test.domain;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;
import se.test.domain.Ying;

privileged aspect Ying_Roo_Jpa_ActiveRecord {
    
    @PersistenceContext
    transient EntityManager Ying.entityManager;
    
    public static final EntityManager Ying.entityManager() {
        EntityManager em = new Ying().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Ying.countYings() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Ying o", Long.class).getSingleResult();
    }
    
    public static List<Ying> Ying.findAllYings() {
        return entityManager().createQuery("SELECT o FROM Ying o", Ying.class).getResultList();
    }
    
    public static Ying Ying.findYing(Long id) {
        if (id == null) return null;
        return entityManager().find(Ying.class, id);
    }
    
    public static List<Ying> Ying.findYingEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Ying o", Ying.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
    @Transactional
    public void Ying.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Ying.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Ying attached = Ying.findYing(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Ying.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Ying.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Ying Ying.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Ying merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
}
