// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package se.test.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Version;
import se.test.domain.Ying;

privileged aspect Ying_Roo_Jpa_Entity {
    
    declare @type: Ying: @Entity;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long Ying.id;
    
    @Version
    @Column(name = "version")
    private Integer Ying.version;
    
    public Long Ying.getId() {
        return this.id;
    }
    
    public void Ying.setId(Long id) {
        this.id = id;
    }
    
    public Integer Ying.getVersion() {
        return this.version;
    }
    
    public void Ying.setVersion(Integer version) {
        this.version = version;
    }
    
}
