// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package se.test.web;

import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;
import se.test.domain.Memo;
import se.test.web.MemoController;

privileged aspect MemoController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String MemoController.create(@Valid Memo memo, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, memo);
            return "memoes/create";
        }
        uiModel.asMap().clear();
        memo.persist();
        return "redirect:/memoes/" + encodeUrlPathSegment(memo.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String MemoController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Memo());
        return "memoes/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String MemoController.show(@PathVariable("id") Long id, Model uiModel) {
        uiModel.addAttribute("memo", Memo.findMemo(id));
        uiModel.addAttribute("itemId", id);
        return "memoes/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String MemoController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("memoes", Memo.findMemoEntries(firstResult, sizeNo));
            float nrOfPages = (float) Memo.countMemoes() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("memoes", Memo.findAllMemoes());
        }
        return "memoes/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String MemoController.update(@Valid Memo memo, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, memo);
            return "memoes/update";
        }
        uiModel.asMap().clear();
        memo.merge();
        return "redirect:/memoes/" + encodeUrlPathSegment(memo.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String MemoController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, Memo.findMemo(id));
        return "memoes/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String MemoController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Memo memo = Memo.findMemo(id);
        memo.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/memoes";
    }
    
    void MemoController.populateEditForm(Model uiModel, Memo memo) {
        uiModel.addAttribute("memo", memo);
    }
    
    String MemoController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
