// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package se.test.web;

import java.io.UnsupportedEncodingException;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import org.joda.time.format.DateTimeFormat;
import org.springframework.context.i18n.LocaleContextHolder;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.util.UriUtils;
import org.springframework.web.util.WebUtils;
import se.test.domain.Ying;
import se.test.web.YingController;

privileged aspect YingController_Roo_Controller {
    
    @RequestMapping(method = RequestMethod.POST, produces = "text/html")
    public String YingController.create(@Valid Ying ying, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, ying);
            return "yings/create";
        }
        uiModel.asMap().clear();
        ying.persist();
        return "redirect:/yings/" + encodeUrlPathSegment(ying.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(params = "form", produces = "text/html")
    public String YingController.createForm(Model uiModel) {
        populateEditForm(uiModel, new Ying());
        return "yings/create";
    }
    
    @RequestMapping(value = "/{id}", produces = "text/html")
    public String YingController.show(@PathVariable("id") Long id, Model uiModel) {
        addDateTimeFormatPatterns(uiModel);
        uiModel.addAttribute("ying", Ying.findYing(id));
        uiModel.addAttribute("itemId", id);
        return "yings/show";
    }
    
    @RequestMapping(produces = "text/html")
    public String YingController.list(@RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        if (page != null || size != null) {
            int sizeNo = size == null ? 10 : size.intValue();
            final int firstResult = page == null ? 0 : (page.intValue() - 1) * sizeNo;
            uiModel.addAttribute("yings", Ying.findYingEntries(firstResult, sizeNo));
            float nrOfPages = (float) Ying.countYings() / sizeNo;
            uiModel.addAttribute("maxPages", (int) ((nrOfPages > (int) nrOfPages || nrOfPages == 0.0) ? nrOfPages + 1 : nrOfPages));
        } else {
            uiModel.addAttribute("yings", Ying.findAllYings());
        }
        addDateTimeFormatPatterns(uiModel);
        return "yings/list";
    }
    
    @RequestMapping(method = RequestMethod.PUT, produces = "text/html")
    public String YingController.update(@Valid Ying ying, BindingResult bindingResult, Model uiModel, HttpServletRequest httpServletRequest) {
        if (bindingResult.hasErrors()) {
            populateEditForm(uiModel, ying);
            return "yings/update";
        }
        uiModel.asMap().clear();
        ying.merge();
        return "redirect:/yings/" + encodeUrlPathSegment(ying.getId().toString(), httpServletRequest);
    }
    
    @RequestMapping(value = "/{id}", params = "form", produces = "text/html")
    public String YingController.updateForm(@PathVariable("id") Long id, Model uiModel) {
        populateEditForm(uiModel, Ying.findYing(id));
        return "yings/update";
    }
    
    @RequestMapping(value = "/{id}", method = RequestMethod.DELETE, produces = "text/html")
    public String YingController.delete(@PathVariable("id") Long id, @RequestParam(value = "page", required = false) Integer page, @RequestParam(value = "size", required = false) Integer size, Model uiModel) {
        Ying ying = Ying.findYing(id);
        ying.remove();
        uiModel.asMap().clear();
        uiModel.addAttribute("page", (page == null) ? "1" : page.toString());
        uiModel.addAttribute("size", (size == null) ? "10" : size.toString());
        return "redirect:/yings";
    }
    
    void YingController.addDateTimeFormatPatterns(Model uiModel) {
        uiModel.addAttribute("ying_duedate_date_format", DateTimeFormat.patternForStyle("M-", LocaleContextHolder.getLocale()));
    }
    
    void YingController.populateEditForm(Model uiModel, Ying ying) {
        uiModel.addAttribute("ying", ying);
        addDateTimeFormatPatterns(uiModel);
    }
    
    String YingController.encodeUrlPathSegment(String pathSegment, HttpServletRequest httpServletRequest) {
        String enc = httpServletRequest.getCharacterEncoding();
        if (enc == null) {
            enc = WebUtils.DEFAULT_CHARACTER_ENCODING;
        }
        try {
            pathSegment = UriUtils.encodePathSegment(pathSegment, enc);
        } catch (UnsupportedEncodingException uee) {}
        return pathSegment;
    }
    
}
